print("Advanced EDA Summary")
print("")
print("Dataset Quality:")
print("- Unicode Coverage:")
print("  - Hindi/Marathi/Konkani: Rich Devanagari coverage (61-74 unique chars)")
print("  - English: Clean Latin script (52 unique chars)")
print("  - Mixed content: Minimal English chars in Indian languages")
print("- Alignment Quality:")
print("  - No empty/very short texts")
print("  - Strong length correlations across language pairs (~0.96-0.97)")
print("  - Consistent character/word length distributions")
print("- Data Integrity:")
print("  - No exact duplicates detected")
print("  - No train/test leakage")
print("  - No missing values")
print("- Language Patterns:")
print("  - Approx word counts (train): Hindi ~29, Marathi/Konkani ~21-22, English ~25")
print("  - English often includes quotes and numbers")
print("  - Indian languages predominantly Devanagari with minimal Latin contamination")
print("")
print("Key Insights:")
print("1) High-quality parallel corpus with excellent alignment")
print("2) Clean train/test split with no leakage")
print("3) Rich multilingual content across 4 languages")
print("4) Ready for machine translation or cross-lingual NLP tasks")
